---
  - name: Configure hosts & deploy application
    hosts: all
    gather_facts: no

    vars:
      mongo_bind_ip: 0.0.0.0
      db_host: 10.128.0.22

    tasks:
      - name: Install git
        become: yes
        apt:
          name: git
          state: present
          update_cache: yes
        tags: app-tag

      - name: Change mongo config file
        become: true
        template:
          src: templates/mongod.conf.j2
          dest: /etc/mongod.conf
          mode: 0644
        tags: db-tag
        notify: restart mongod

      - name: Add unit file for Puma
        become: yes
        copy:
          src: files/puma.service
          dest: /etc/systemd/system/puma.service
        tags: app-tag
        notify: reload puma

      - name: Add config for DB connection
        template:
          src: templates/db_config.j2
          dest: /home/ubuntu/db_config
        tags: app-tag

      - name: enable puma
        become: yes
        systemd:
          name: puma
          enabled: yes
        tags: app-tag

      - name: Fetch the latest version of application code
        git:
          repo: 'https://github.com/express42/reddit.git'
          dest: /home/ubuntu/reddit
          version: monolith
        tags: deploy-tag
        notify: reload puma

      - name: Bundle install
        bundler:
          state: present
          chdir: /home/ubuntu/reddit
        tags: deploy-tag

    handlers:
      - name: restart mongod
        become: yes
        service:
          name: mongod
          state: restarted

      - name: reload puma
        become: yes
        systemd:
          name: puma
          state: restarted
